---
title: "SPS-DATA607-ASSIGNMENT-2-1"
author: "Tage N Singh"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

## **MULTI-TABLE SURVEY PROJECT**

#### The survey was designed and published to classmates and Linkedin participants using **SurveyMonkey**
#### The NETFLIX data was provided by **https://www.kaggle.com/**

##### You can participate in the survey by clicking on this link **https://www.surveymonkey.com/r/RGWG7Q7**

##### The native SurveyMonkey results can be viewed with this link (**Note** that the project database updates are manual) **https://www.surveymonkey.com/stories/SM-LBNGF732/**

&nbsp;

##### **The GitHub Repository for this project is located here:**
##### https://github.com/tagensingh/SPS-DATA607-ASSIGNMENT-2.git

&nbsp;

### **The steps to build this project database are as follows:** 
#All required files are in the GitHub Repository provided above.

##### 1. Create a MySQL schema called **"shows"** by executing the **"1-create-shows.sql"** script from within the MySQL DBMS

##### 2. Copy the following files to the MySql/data/shows  directory.(This is the directory where your DBMS would create the datails for the 'shows' database from the script above) - **1-data-add-survey-all.csv** - and - **1-netflix-shows-ratings-all.csv**

##### 3. Create the tables **"survey"**, **"netflixratings"** and populate them by executing the script **"1-add-records-shows-all.sql"**

### Note - This solution assumes a local install of the MySQL database, hence the credentials used are unique to the user enviroment

#___________________________________________________________________________________________________

**THE DATABASE IS READY FOR USE**

#____________________________________________________________________________________________________

&nbsp;

#### To execute the code of sample queries for this database project, please open and render the file below located in the repository - 

**https://github.com/tagensingh/SPS-DATA607-ASSIGNMENT-2.git**

#### **('SPS-DATA607-ASSIGNMENT-2-2.rmd')**
